#@ load("@ytt:data", "data")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpack-controller
  namespace: kpack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack-controller
  template:
    metadata:
      labels:
        app: kpack-controller
        version: #@ data.values.version
    spec:
      serviceAccountName: controller
      containers:
      - name: controller
        image: #@ data.values.controller_image
        env:
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: CONFIG_OBSERVABILITY_NAME
          value: config-observability
        - name: METRICS_DOMAIN
          value: kpack.io
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

        - name: BUILD_INIT_IMAGE
          value: #@ data.values.build_init_image
        - name: REBASE_IMAGE
          value: #@ data.values.rebase_image
        - name: COMPLETION_IMAGE
          value: #@ data.values.completion_image
        - name: LIFECYCLE_IMAGE
          value: #@ data.values.lifecycle_image
