name: CI

on:
  push:
    branches:
    - main
  pull_request: {}

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: '1.15'
    - name: Run tests
      run: make unit-ci
    - name: Report coverage
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: 4e256ab5-d474-459d-8d4d-cffea6455db7
